name: Weekly Pokemon Card Database Update

on:
  schedule:
    # Run every Sunday at 6 AM UTC (adjust timezone as needed)
    - cron: '0 6 * * 0'
  workflow_dispatch: # Allow manual trigger

jobs:
  update-cards:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        cd scripts
        pip install -r requirements.txt
        
    - name: Run card database update
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        POKEMON_TCG_API_KEY: ${{ secrets.POKEMON_TCG_API_KEY }}
      run: |
        python scripts/weekly_update.py
        
    - name: Notify on failure
      if: failure()
      run: |
        echo "Weekly card update failed - check logs"
        # You could add Slack/Discord notification here